version: '3.5'
services:
  webapp-server :
    hostname: websphere
    image: websphere-liberty:webProfile6
    ports:
      - "9080:9080"
    volumes:
      - ./target/javaee6-example.war:/config/dropins/SampleJEE6.war